name: Script

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Release with steamdb_changelist_grabber.user.js
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            steamdb_changelist_grabber.user.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}